### PR TITLE
Fix #113

### LINKED ISSUE #113: Multiple import form for __future__ imports confuses futurize
Running `futurize -1 -a -w file.py` on a file that contains `from __future__ import (division, print_statement)` (from some previous work, for example), fails with:

```
Traceback (most recent call last):
  File "/usr/bin/futurize", line 9, in <module>
    load_entry_point('future==0.14.1', 'console_scripts', 'futurize')()
  File "/usr/lib/python2.7/site-packages/libfuturize/main.py", line 295, in main
    options.processes)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 706, in refactor
    items, write, doctests_only)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 301, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 747, in refactor_file
    *args, **kwargs)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 354, in refactor_file
    tree = self.refactor_string(input, filename)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 386, in refactor_string
    self.refactor_tree(tree, name)
  File "/usr/lib64/python2.7/lib2to3/refactor.py", line 460, in refactor_tree
    new = fixer.transform(node, results)
  File "/usr/lib/python2.7/site-packages/libfuturize/fixes/fix_add__future__imports_except_unicode_literals.py", line 24, in transform
    future_import(u"print_function", node)
  File "/usr/lib/python2.7/site-packages/libfuturize/fixer_util.py", line 210, in future_import
    names = check_future_import(node)
  File "/usr/lib/python2.7/site-packages/libfuturize/fixer_util.py", line 424, in check_future_import
    assert False, "strange import: %s" % savenode
AssertionError: strange import: 
from __future__ import (division, print_function)
```

~~Note: Multiple imports on one line are usually against PEP8, but it seems that pep8 doesn't mind it with `__future__` imports...~~ Sorry, `import x, y, z` is against PEP8, but `from a import x, y z` is fine.

### PR DESCRIPTION
**Pull request by flaviut**

### CODE REVIEW

**Comment by jmadler** [comment]
Would you be comfortable adding a unit test for this?

**Comment by flaviut** [comment]
Sure, just give me a few moments. Do you know what's going on with this project? There haven't been any updates in a while.

**Comment by jmadler** [comment]
Thanks!

I spoke with @edschofield yesterday and I'm going to help him maintain python-future going forward.  We're using it heavily at Pinterest at the moment and we have a few bugs we've discovered and patches we'd like to share upstream :)

**Comment by jmadler** [comment]
Perfect!  Thank you so much :)

**Comment by flaviut** [comment]
Oh, sorry, I should have marked it WIP!

I noticed that a couple of the other tests failed with this change, and I haven't figured out why yet. Can you please revert this?

**Comment by flaviut** [comment]
Can you please take a look at #361? It fixes the regression that this PR introduced, and is a 1-line change.

**Comment by jmadler** [comment]
Will do, thanks.  I assumed the test failures were a result of the known issues with 3.5+, but that was clearly in error.  Great eye :)

**Pull request merged**
