### PR TITLE
`from builtins import itervalues` doesn't work with python 2.7

### PR DESCRIPTION
**Pull request by theoden-dd**
I hope auto-trimmed spaces are OK.

### CODE REVIEW

**Comment by Uzume** [comment]
I noticed the same documentation issue on the website:
Cheat Sheet: Writing Python 2-3 compatible code Dictionaries [Iterating through dict keys/values/items](http://python-future.org/compatible_idioms.html#iterating-through-dict-keys-values-items)

**Comment by sfdye** [comment]
Sorry could you remove the non essential changes, it's very hard to review

**Comment by Uzume** [comment]
This was fixed with 9fcde90f29b6e278417dac243170ebb79ce65283, however, the website still reports the same older broken content and appears to be need to be regenerated.

Please have these updated from [docs/compatible_idioms.rst](../blob/master/docs/compatible_idioms.rst):
- https://python-future.org/compatible_idioms.html
- http://python-future.org/compatible_idioms.pdf

This:
```python
from builtins import itervalues
```
needs to be changed to:
```python
from future.utils import itervalues
```

Since the change was made in 2018, it appears the website has not been updated in years.

This also seems to affect other things that have the same error in them, like:
- [PythonCharmers/PythonCharmersDocs/Python 2-3 Compatibility](/PythonCharmers/PythonCharmersDocs/tree/master/Python%202-3%20Compatibility)

Thank you.

**Comment by sfdye** [comment]
I see, thanks! For website update we have #511, which will be fixed very soon.

**Pull request closed without merging**
