### PR TITLE
add unit test to prove the behaviour for string equality

### PR DESCRIPTION
**Pull request by shivapbhusal**

### CODE REVIEW

**Comment by jmadler** [comment]
Thanks for helping address #432 :)

**Comment by ethanfurman** [comment]
This patch was committed before you heard back from the Python Dev team?  That seems premature.

It's also a useless test since the only thing stringy about `OurCustomString` is the name.  To be a correct test you need to add the `__eq__` method that Max-Volger showed in his example:

    def __eq__(self, other):
        if isinstance(other, (str, newstr)):
            return self.string == other
        else:
            return NotImplemented

You should probably also add a test to make sure `OurCustomString` compares correctly to a regular string:

    self.assertTrue(our_str == 'foobar')

**Comment by jmadler** [comment]
Hi @ethanfurman!  I asked @shivapbhusal to write a unit test to confirm the behavior of the design of the function until the design was able to be discussed.  I'm sorry this wasn't shared publicly.  If you have further comment after the changes made since that conversation has ended please file a new bug.

@shivapbhusal thanks for your first open source contribution.  You've done a great job and I look forward to hearing more from you :) See you at the next PyCon!

**Comment by shivapbhusal** [comment]
Hi @jmadler, Thanks a lot for helping me get started. I look forward to making more contributions in the future. See you at the next PyCon!

**Pull request merged**
