### PR TITLE
Do not globally destroy re.ASCII in PY3

### PR DESCRIPTION
**Pull request by rectalogic**

### CODE REVIEW

**Comment by rectalogic** [comment]
This is breaking our python 3 port. We cannot avoid these modules because a 3rd party dependency is importing them and so globally wiping out re.ASCII, which breaks our code and other depencies we have:
https://github.com/OpenIDC/pyoidc/blob/v0.15.1/src/oic/utils/http_util.py#L1

@jmadler any way we can get a release that includes this PR?

**Comment by jmadler** [comment]
@rectalogic I was planning on doing a sprint around the week of March 11th with a release shortly thereafter.  Does that timeline work for you, or do you need a special cut?

**Comment by rectalogic** [comment]
Yeah that's OK, thanks. I found a workaround by pre-emptively importing those modules then fixing re.ASCII:
```python
import future.utils
if future.utils.PY3:
    import re
    save = re.ASCII
    from future.backports.http import cookies, cookiejar  # noqa: F401
    re.ASCII = save
```

**Comment by jmadler** [comment]
@rectalogic Awesome.  I missed the timeline I expected to able to hit, but we're reaching a good state for 0.18 so expect a release soon :)

**Pull request merged**
